/* ── DASHBOARD ──
   Mock printer dashboard with simulated real-time updates.
   All data is fake / demo-mode. No actual printer connection.
*/

(function() {
  'use strict';

  /* ── State ── */
  var state = {
    status: 'Printing',
    progress: 67,
    tempHotend: 215,
    tempBed: 60,
    targetHotend: 220,
    targetBed: 60,
    file: 'geometric_vase_v3.gcode',
    timeRemaining: 6120, // seconds
    paused: false,
    stopped: false,
    gcodeActiveLine: 12
  };

  /* ── DOM refs ── */
  var els = {
    status: document.getElementById('printer-status'),
    statusDot: document.getElementById('status-dot'),
    file: document.getElementById('current-file'),
    gaugeFill: document.getElementById('gauge-fill'),
    gaugeText: document.getElementById('gauge-text'),
    timeRemaining: document.getElementById('time-remaining'),
    tempHotend: document.getElementById('temp-hotend'),
    tempBed: document.getElementById('temp-bed'),
    tempHotendBar: document.getElementById('temp-hotend-bar'),
    tempBedBar: document.getElementById('temp-bed-bar'),
    gcodePreview: document.getElementById('gcode-preview'),
    consoleOutput: document.getElementById('console-output'),
    toastContainer: document.getElementById('toast-container'),
    btnPause: document.getElementById('btn-pause'),
    btnStop: document.getElementById('btn-stop'),
    btnHome: document.getElementById('btn-home'),
    btnCooldown: document.getElementById('btn-cooldown')
  };

  /* ── SVG gauge constants ── */
  var GAUGE_CIRCUMFERENCE = 2 * Math.PI * 54; // r=54

  /* ── Mock G-code ── */
  var gcodeLines = [
    '; generated by Alpaca3D Slicer',
    '; geometric_vase_v3.gcode',
    'G28 ; Home all axes',
    'G29 ; Auto bed leveling',
    'M104 S220 ; Set hotend temp',
    'M140 S60 ; Set bed temp',
    'M190 S60 ; Wait for bed',
    'M109 S220 ; Wait for hotend',
    'G92 E0 ; Reset extruder',
    'G1 Z2.0 F3000 ; Move Z up',
    'G1 X10 Y20 F5000 ; Move to start',
    'G1 Z0.28 F1000 ; First layer height',
    'G1 X110 Y20 E12.5 F1500 ; Print line',
    'G1 X110 Y120 E25.0 F1500 ; Print line',
    'G1 X10 Y120 E37.5 F1500 ; Print line',
    'G1 X10 Y20 E50.0 F1500 ; Close perimeter',
    'G1 E49.0 F2400 ; Retract',
    'G1 Z0.56 F3000 ; Layer 2',
    'G1 X12 Y22 F5000 ; Move to start',
    'G1 E50.0 F2400 ; De-retract',
    'G1 X108 Y22 E62.5 F1800 ; Print line',
    'G1 X108 Y118 E75.0 F1800 ; Print line',
    'G1 X12 Y118 E87.5 F1800 ; Print line',
    'G1 X12 Y22 E100.0 F1800 ; Close perimeter',
    'G1 E99.0 F2400 ; Retract',
    'G1 Z0.84 F3000 ; Layer 3'
  ];

  /* ── Console messages pool ── */
  var consoleMsgs = [
    'ok T:215.2 /220 B:60.1 /60',
    'echo: Layer 142/347 complete',
    'echo: Fan speed set to 100%',
    'ok P15 B3 T:215.0 /220 B:60.0 /60',
    'echo: Acceleration set to 3000 mm/s^2',
    'echo: Print speed: 150 mm/s',
    'ok T:214.8 /220 B:59.9 /60',
    'echo: Retraction: 0.8mm @ 45mm/s',
    'echo: Flow rate: 98%',
    'ok T:215.5 /220 B:60.2 /60',
    'echo: Z-offset: -0.05mm',
    'echo: Estimated filament: 24.3m / 72.1g',
    'ok T:215.1 /220 B:60.0 /60',
    'echo: Pressure advance: 0.045',
    'echo: Input shaper: MZV @ 48.2Hz'
  ];

  /* ── Utility ── */
  function formatTime(seconds) {
    var h = Math.floor(seconds / 3600);
    var m = Math.floor((seconds % 3600) / 60);
    if (h > 0) return h + 'h ' + m + 'm';
    return m + 'm';
  }

  function getTimestamp() {
    var now = new Date();
    var hh = String(now.getHours()).padStart(2, '0');
    var mm = String(now.getMinutes()).padStart(2, '0');
    var ss = String(now.getSeconds()).padStart(2, '0');
    return hh + ':' + mm + ':' + ss;
  }

  function randomFluctuation(value, range) {
    return value + (Math.random() - 0.5) * range * 2;
  }

  /* ── Render G-code preview ── */
  function renderGcode() {
    if (!els.gcodePreview) return;
    var html = '';
    for (var i = 0; i < gcodeLines.length; i++) {
      var isActive = i === state.gcodeActiveLine;
      var lineNum = String(i + 1).padStart(3, ' ');
      html += '<div class="gcode-line' + (isActive ? ' active' : '') + '">' +
              '<span class="gcode-linenum">' + lineNum + '</span>' +
              '<span class="gcode-text">' + escapeHtml(gcodeLines[i]) + '</span>' +
              '</div>';
    }
    els.gcodePreview.innerHTML = html;

    /* Auto-scroll to active line */
    var activeLine = els.gcodePreview.querySelector('.gcode-line.active');
    if (activeLine) {
      activeLine.scrollIntoView({ block: 'center', behavior: 'smooth' });
    }
  }

  function escapeHtml(str) {
    return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }

  /* ── Update gauge ── */
  function updateGauge() {
    if (!els.gaugeFill || !els.gaugeText) return;
    var offset = GAUGE_CIRCUMFERENCE - (state.progress / 100) * GAUGE_CIRCUMFERENCE;
    els.gaugeFill.style.strokeDashoffset = offset;
    els.gaugeText.textContent = Math.round(state.progress) + '%';
  }

  /* ── Update temperatures ── */
  function updateTemps() {
    var hotendDisplay = Math.round(state.tempHotend);
    var bedDisplay = Math.round(state.tempBed);

    if (els.tempHotend) els.tempHotend.textContent = hotendDisplay + '\u00B0C';
    if (els.tempBed) els.tempBed.textContent = bedDisplay + '\u00B0C';

    /* Bar widths: scale hotend 0-280, bed 0-120 */
    if (els.tempHotendBar) els.tempHotendBar.style.width = Math.min(100, (hotendDisplay / 280) * 100) + '%';
    if (els.tempBedBar) els.tempBedBar.style.width = Math.min(100, (bedDisplay / 120) * 100) + '%';
  }

  /* ── Console log ── */
  function addConsoleLine(msg) {
    if (!els.consoleOutput) return;
    var line = document.createElement('div');
    line.className = 'console-line';
    line.innerHTML = '<span class="console-ts">[' + getTimestamp() + ']</span> ' + msg;
    els.consoleOutput.appendChild(line);

    /* Keep max 50 lines */
    while (els.consoleOutput.children.length > 50) {
      els.consoleOutput.removeChild(els.consoleOutput.firstChild);
    }

    /* Auto-scroll */
    els.consoleOutput.scrollTop = els.consoleOutput.scrollHeight;
  }

  /* ── Toast notifications ── */
  function showToast(message, type) {
    if (!els.toastContainer) return;
    var toast = document.createElement('div');
    toast.className = 'toast toast-' + (type || 'info');
    toast.textContent = message;
    els.toastContainer.appendChild(toast);

    setTimeout(function() {
      toast.classList.add('toast-exit');
      setTimeout(function() {
        if (toast.parentNode) toast.parentNode.removeChild(toast);
      }, 300);
    }, 3000);
  }

  /* ── Update status display ── */
  function updateStatus() {
    if (els.status) els.status.textContent = state.status;
    if (els.file) els.file.textContent = state.file;
    if (els.timeRemaining) els.timeRemaining.textContent = 'Est. ' + formatTime(state.timeRemaining) + ' remaining';

    if (els.statusDot) {
      els.statusDot.className = 'status-indicator';
      if (state.stopped) {
        els.statusDot.classList.add('offline');
      } else if (state.paused) {
        els.statusDot.classList.add('warning');
      } else {
        els.statusDot.classList.add('online');
      }
    }
  }

  /* ── Simulation tick (every 2 seconds) ── */
  var tickInterval = setInterval(function() {
    if (state.stopped) return;

    if (!state.paused) {
      /* Progress increment */
      state.progress = Math.min(100, state.progress + 0.15 + Math.random() * 0.1);

      /* Time countdown */
      state.timeRemaining = Math.max(0, state.timeRemaining - 2);

      /* Temperature fluctuation */
      state.tempHotend = randomFluctuation(state.targetHotend, 1.5);
      state.tempBed = randomFluctuation(state.targetBed, 0.8);

      /* Advance G-code active line */
      if (Math.random() > 0.6) {
        state.gcodeActiveLine = (state.gcodeActiveLine + 1) % gcodeLines.length;
      }

      /* Random console output */
      if (Math.random() > 0.4) {
        var msg = consoleMsgs[Math.floor(Math.random() * consoleMsgs.length)];
        addConsoleLine(msg);
      }
    }

    updateGauge();
    updateTemps();
    updateStatus();
    renderGcode();

    /* Check completion */
    if (state.progress >= 100 && !state.stopped) {
      state.status = 'Complete';
      state.timeRemaining = 0;
      showToast('Print complete! Remove part from bed.', 'success');
      clearInterval(tickInterval);
    }
  }, 2000);

  /* ── Button handlers ── */
  if (els.btnPause) {
    els.btnPause.addEventListener('click', function() {
      if (state.stopped) return;
      state.paused = !state.paused;
      state.status = state.paused ? 'Paused' : 'Printing';
      els.btnPause.textContent = state.paused ? 'Resume' : 'Pause';
      showToast(state.paused ? 'Print paused' : 'Print resumed', 'info');
      addConsoleLine(state.paused ? 'echo: Print PAUSED by user' : 'echo: Print RESUMED');
      updateStatus();
    });
  }

  if (els.btnStop) {
    els.btnStop.addEventListener('click', function() {
      state.stopped = true;
      state.paused = false;
      state.status = 'Stopped';
      showToast('Print cancelled', 'error');
      addConsoleLine('echo: EMERGENCY STOP - Print cancelled by user');
      addConsoleLine('echo: Cooling down...');
      updateStatus();
    });
  }

  if (els.btnHome) {
    els.btnHome.addEventListener('click', function() {
      showToast('Home command sent', 'info');
      addConsoleLine('echo: G28 - Homing all axes...');
      addConsoleLine('echo: X homed, Y homed, Z homed');
    });
  }

  if (els.btnCooldown) {
    els.btnCooldown.addEventListener('click', function() {
      state.targetHotend = 0;
      state.targetBed = 0;
      showToast('Cooldown initiated', 'info');
      addConsoleLine('echo: M104 S0 - Hotend cooling');
      addConsoleLine('echo: M140 S0 - Bed cooling');
    });
  }

  /* ── Initial render ── */
  updateGauge();
  updateTemps();
  updateStatus();
  renderGcode();

  /* Initial console messages */
  addConsoleLine('echo: Alpaca3D Dashboard connected (DEMO MODE)');
  addConsoleLine('echo: Printer: Flashforge AD5M Pro');
  addConsoleLine('echo: Firmware: Klipper v0.12.0');
  addConsoleLine('echo: File loaded: ' + state.file);
  addConsoleLine('ok T:215.0 /220 B:60.0 /60');
})();
